[tool.briefcase]
project_name = "SkillSwap iOS"
bundle = "com.skillswap"
version = "0.0.1"
url = "https://example.com"
license = "MIT"
author = "SkillSwap"
author_email = "hello@example.com"

[tool.briefcase.app.skillswap_ios]
formal_name = "SkillSwap iOS"
description = "iOS client for SkillSwap"
sources = ["skillswap_ios"]
requires = ["toga-iOS>=0.4.7"]
